# Generated by Django 4.0.4 on 2022-06-28 03:33

import base.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_catroom_options_alter_meow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meow',
            options={},
        ),
        migrations.AlterField(
            model_name='catroom',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meow',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
